### ISSUE TITLE
notebook 5 / hmm memberships

### ISSUE THREAD

**Issue by franknoe** [markovmodel/pyemma_tutorials#69] opened 2018-06-29 21:44 UTC
In this plot the visualization makes a discretization error in the assignment of the transition state region. In this region an clear assignment is not possible. It would be better to somehow show the fuzzy assignment (membership). Maybe that's best done in four plots, but perhaps there is a pallette that also works in one plot.

![image](https://user-images.githubusercontent.com/6495810/42116138-4e609d2a-7bf6-11e8-9d7b-094af31434e3.png)

**Comment by franknoe** [comment] 2018-06-29 21:52
Same here, and maybe elsewhere

![image](https://user-images.githubusercontent.com/6495810/42116408-69529434-7bf7-11e8-8e54-01c229166fe4.png)

**Comment by cwehmeyer** [comment] 2018-06-29 21:53
I'll have a look whether that is plotting-related or caused by the metastable assignment.

**Comment by cwehmeyer** [comment] 2018-07-02 14:19
This is not a bug but the result of a very sparse clustering.

**Comment by thempel** [comment] 2018-07-05 16:00
Issue resolved by #83 and `pyemma.plots` update (thanks @cwehmeyer and @marscher).

**Closed by thempel** 2018-07-05 16:00 UTC
Labels: enhancement, notebook
