### ISSUE TITLE
matplotlib rendering error

### ISSUE THREAD

**Issue by marscher** [markovmodel/pyemma_tutorials#180] opened 2018-11-15 20:59 UTC
In nb08 this exception is raised during rendering the figure produced by plot_1D_histogram_trajectories.
When I comment out the ax.annotate call, then the figure is rendered correctly. I assume this is triggered by a rigorous check, which has been added recently. I will report it upstream.

In the meantime we can simply downgrade matplotlib for test execution.

**Comment by thempel** [comment] 2018-11-16 09:38
I guess it's the `plt.annotate` because they changed the API. Maybe I can fix that.

**Comment by marscher** [comment] 2018-11-16 09:47
On 16.11.18 10:38, Tim Hempel wrote:
> I guess it's the `plt.annotate` because they changed the API. Maybe I can fix that.
> 
if I omit the arrowprops it succeeds.

**Comment by thempel** [comment] 2018-11-19 08:20
Bug was reported to Matplotlib (https://github.com/matplotlib/matplotlib/issues/12820), for now resolved with #181 .

**Closed by thempel** 2018-11-19 08:20 UTC

**Comment by photoniker** [comment] 2019-02-28 20:53
I sill get this bug, in the case of saving the figure as an image (format png, jpg, tiff). Saving it as a pdf works! 
The problem is the annotate function.

**Comment by thempel** [comment] 2019-02-28 21:00
OK, interesting. We'll have to wait for the matplotlib developers to really fix this (it's reported, cf. post above). Good that you can save it to PDF, so I suggest you stick to this as a temporary solution (and convert to png/jpeg if necessary).

**Comment by photoniker** [comment] 2019-02-28 21:05
> I sill get this bug, in the case of saving the figure as an image (format png, jpg, tiff). Saving it as a pdf works!
> The problem is the annotate function.

Maybe this helps to find the bug. If I add to the x-position a tiny distance of 0.000000000001, than is works: 
axarr[0].annotate('', xy=(objectZValues[3]+0.000000000001, objectIntensities[3]), xytext=(objectZValues[3],-.05), bbox=dict(boxstyle="round", fc="w"), arrowprops = settings.arrowProps)

**Comment by thempel** [comment] 2019-02-28 21:16
Yes, this is how we temporarily fixed this bug here. Are you sure you are posting to the right repository?

**Comment by photoniker** [comment] 2019-02-28 21:44
@thempel oh sorry, I was redirected here.
